[workspace]
members = [
    "p01-calorie-counting",
    "p02-rock-paper-scissors",
    "p03-rucksack-reorganization",
    "p04-camp-cleanup"
]

[workspace.dependencies]
clap = { version = "4.0.29", features = [ "derive" ] }
